### ISSUE TITLE
Fixed in https://github.com/BryceCanyonCounty/bcc-camp/pull/10

### ISSUE THREAD

**Issue by reserect** [BryceCanyonCounty/bcc-camp#11]
Fixed in https://github.com/BryceCanyonCounty/bcc-camp/pull/10

_Originally posted by @AndrewR3K in https://github.com/BryceCanyonCounty/bcc-camp/issues/9#issuecomment-2174273184_

Seems to be doing it still for some reason i cleared cache too

**Comment by reserect** [comment]
Think you need to update releases

**Comment by reserect** [comment]
[    script:bcc-utils] (CACHED)❌Outdated! [bcc-camp] (Version 1.0.4)
[    script:bcc-utils] NEW VERSION (1.0.5) <https://github.com/BryceCanyonCounty/bcc-camp/releases/tag/1.0.5>
[    script:bcc-utils] CHANGELOG 
[    script:bcc-utils] * Complete rewrite for language support
[    script:bcc-utils] 
[    script:bcc-utils] Revamped code structure to enhance readability and maintainability, ensuring clarity and ease of future updates.
[    script:bcc-utils] 
[    script:bcc-utils] Added support for Romanian language also
[    script:bcc-utils] 
[    script:bcc-utils] change blip from campSetup to bcc-utils
[    script:bcc-utils] 
[    script:bcc-utils] * Update CampSetup.lua

**Comment by AndrewR3K** [comment]
it's cached. Clear the version cache in bcc-utils.

server/cache/version.json save content in this file as {}

**Comment by reserect** [comment]
That seems to have sorted it haha Thank you for the help.
