### ISSUE TITLE
seems to be a slight error in the version check for this 

### ISSUE THREAD

**Issue by yaboibutt3r** [BryceCanyonCounty/bcc-camp#13]
[    script:bcc-utils] ❌Outdated! [bcc-camp] (Version 1.0.6)
[    script:bcc-utils] NEW VERSION (1.4.17) <https://github.com/BryceCanyonCounty/bcc-stables>
[    script:bcc-utils] ^CHANGELOG 
[    script:bcc-utils] <1.4.17>
[    script:bcc-utils] See GitHub for details!

**Comment by iseeyoucopy** [comment]
You can find a fix in here #14
